# Nama workflow yang akan tampil di tab Actions GitHub
name: Run FastAPI Server Test

# Pemicu: Kapan workflow ini akan berjalan?
# Di sini, ia akan berjalan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches: [ main ]

# Pekerjaan (jobs) yang akan dilakukan
jobs:
  build:
    # Sistem operasi yang digunakan (virtual machine)
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dieksekusi
    steps:
      # 1. Mengunduh kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Menyiapkan lingkungan Python versi 3.9
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Menginstal library yang ada di requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Menjalankan server FastAPI sebagai tes
      #    Di sinilah kita menggunakan Secret!
      - name: Run FastAPI Server
        env:
          # Ini akan mengambil nilai dari Secret yang Anda buat
          # dan memasukkannya ke environment variable
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          # Menjalankan server di background selama beberapa detik untuk memastikan tidak ada error
          uvicorn index:app --host 0.0.0.0 --port 8000 &
          sleep 5
          echo "Server test completed."
